### ISSUE TITLE
[BUG] keyframes 定义了带小数的step会出错

### ISSUE THREAD

**Issue by Genuifx** [wechat-miniprogram/miniprogram-simulate#29]
由于wxss处理的时候[正则](https://github.com/wechat-miniprogram/miniprogram-simulate/blob/a6c8dff1d7b813b5f7c90bfe918e46492ca475d4/src/wxss.js#L21)的有问题导致，添加前缀错误，进而影响csso压缩。

```css
@-webkit-keyframes headShake {
  0% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
  }

  6.5% {
    -webkit-transform: translateX(-6px) rotateY(-9deg);
    transform: translateX(-6px) rotateY(-9deg);
  }

  18.5% {
    -webkit-transform: translateX(5px) rotateY(7deg);
    transform: translateX(5px) rotateY(7deg);
  }

  31.5% {
    -webkit-transform: translateX(-3px) rotateY(-5deg);
    transform: translateX(-3px) rotateY(-5deg);
  }

  43.5% {
    -webkit-transform: translateX(2px) rotateY(3deg);
    transform: translateX(2px) rotateY(3deg);
  }

  50% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
  }
}

.main {
}
```
